language: bash
addons:
  apt:
    packages:
    - whois
    - gawk
    - mawk
    - original-awk
    - mksh
    - posh
    - dash
    - bash

before_install:
  # Grab ShellCheck from the Debian repo
  # install shellcheck after other packages already installed from Ubuntu repo
  # https://github.com/koalaman/shellcheck/issues/941
  - curl -sSL "https://ftp-master.debian.org/keys/archive-key-7.0.asc" | sudo -E apt-key add -
  - echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install shellcheck

env:
  - AWK=awk
  - AWK=mawk
  - AWK=gawk
  - AWK=original-awk
  - SH=sh
  - SH=mksh
  - SH=posh
  - SH=dash
  - SH=bash

script:
  - shellcheck check_domain.sh
  - ./test.sh

# vim:ts=2:sw=2:et
